### ISSUE TITLE
Gentoo will be removing dev-python/cgroup-utils

### ISSUE THREAD

**Issue by TerraTech** [peo3/cgroup-utils#11]
Any chance of updating for compatibility with Python >=3.7 ?

```
- dev-python/cgroup-utils-0.6::gentoo (masked by: package.mask)
/usr/portage/profiles/package.mask:
# Michal Górny <mgorny@gentoo.org> (2020-03-07)
# The following packages are stuck on Python 3.6, and have no reverse
# dependencies.  Please let the Python team know if you find some
# of them still useful.
# Removal in 30 days.  Bug #711808.
```

**Comment by peo3** [comment]
I'm sorry for late replying and thank you for letting me know that.

At least cgroup-utils 0.8 can work with python 3.7.  So I guess updating the package in the Gentoo package repository to 0.8 with modifying the ebuild file as `PYTHON_COMPAT=( python3_7 )` resolve the issue?

**Comment by TerraTech** [comment]
I created a new ebuild for ```dev-python/cgroup-utils-0.8``` using the updated 
```PYTHON_COMPAT=( python3_{6,7} )```

It built and worked fine.

For reference:  https://bugs.gentoo.org/711808#c59

**Comment by hartwork** [comment]
I have averted removal from Gentoo and bumped to 0.8 now in https://github.com/gentoo/gentoo/commit/10233b368e888c075f84dd3b673c70dd009e7cff .

Related: pull request #12

**Comment by peo3** [comment]
Thank you very much for keeping the package available on Gentoo!

>Related: pull request #12

I've merged the changes.  Thanks!
