### ISSUE TITLE
cgutil top fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by f18m** [peo3/cgroup-utils#8]
Just installed cgroup-utils

```
root@francesco-X8SIL:~# pip show cgroup-utils
Name: cgroup-utils
Version: 0.5
Summary: Utility tools for control groups of Linux
Home-page: https://github.com/peo3/cgroup-utils
Author: peo3
Author-email: peo314159265@gmail.com
License: GPLv2
Location: /usr/local/lib/python2.7/dist-packages
Requires: argparse, multiprocessing
```

and tried to launch cgutil top:

```
# cgutil top
Traceback (most recent call last):
  File "/usr/local/bin/cgutil", line 48, in <module>
    main()
  File "/usr/local/bin/cgutil", line 44, in main
    cmd.run()
  File "/usr/local/lib/python2.7/dist-packages/cgutils/commands/top.py", line 524, in run
    return curses.wrapper(self._run_window)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/cgutils/commands/top.py", line 518, in _run_window
    ui.run()
  File "/usr/local/lib/python2.7/dist-packages/cgutils/commands/top.py", line 318, in run
    self.cgstats.update()
  File "/usr/local/lib/python2.7/dist-packages/cgutils/commands/top.py", line 212, in update
    stats = _cgroup.get_stats()
  File "/usr/local/lib/python2.7/dist-packages/cgutils/cgroup.py", line 665, in get_stats
    stats[name] = self._PARSERS[cls](fileops.read(path))
  File "/usr/local/lib/python2.7/dist-packages/cgutils/cgroup.py", line 269, in parse
    raise EnvironmentError('No header found in memory.kmem.slabinfo')
EnvironmentError: No header found in memory.kmem.slabinfo
```

```
# uname -a
Linux francesco-X8SIL 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ozaki-r** [comment]
It seems that Linux has changed the content of memory.kmem.slabinfo, which causes the error.
Could you try cgroup-utils 0.7?  It should fix the issue.

**Comment by peo3** [comment]
(Oops!  I replied with a different account...  Please ignore the message if you saw it.)

It seems that Linux has changed the content of memory.kmem.slabinfo, which causes the error.
Could you try cgroup-utils 0.7? It should fix the issue.

**Comment by f18m** [comment]
Hi @peo3,
I just upgraded to version 0.7 and "cgutil top" now works, thanks!

A question though: it shows only usr/sys CPU stats for the "cpuacct" cgroup. 
I understand that such cgroup only provides such stats but would it be possible to look instead at the (more detailed) stats for the CPUs used by the container from /proc/stat (see http://www.linuxhowtos.org/System/procstat.htm) ?

I think the CPUs assigned to the container can be read from the "cpuset" cgroup...

Thanks

**Comment by peo3** [comment]
> Hi @peo3,
> I just upgraded to version 0.7 and "cgutil top" now works, thanks!

Good :)

> 
> A question though: it shows only usr/sys CPU stats for the "cpuacct" cgroup.
> I understand that such cgroup only provides such stats but would it be possible to look instead at the (more detailed) stats for the CPUs used by the container from /proc/stat (see http://www.linuxhowtos.org/System/procstat.htm) ?
> 
> I think the CPUs assigned to the container can be read from the "cpuset" cgroup...

As you said, this tool is specific to cgroup and so it should use only stats provided by cgroup.
I have no plan to extend this tool to adapt containers (at least in this project).

**Comment by f18m** [comment]
Ok thanks, good to know. I'm then closing this issue!
