### ISSUE TITLE
pip install does not install latest released version from pypi.org

### ISSUE THREAD

**Issue by wuxxin** [peo3/cgroup-utils#9]
+ reproduction: 
```
pip3 install "cgroup-utils"
# version 0.5 is trying to get installed but fails because 0.5 is not py3 compatible
pip3 install "cgroup-utils>=0.6" 
# fails because pip says there is no 0.6
```
+ while debugging i found that: `https://pypi.org/simple/cgroup-utils/` only lists package versions 0.3, 0.4, 0.5, but while cross checking with other pypi packages latest version is always in "/simple"

**Comment by ozaki-r** [comment]
I don't know why the package of 0.6 is not uploaded...
Anyway I've uploaded it and also that of 0.7 which has been released a little while ago.
Could you try again?

**Comment by peo3** [comment]
(Oops!  I replied with a different account...  Please ignore the message if you saw it.)

I don't know why the package of 0.6 is not uploaded...
Anyway I've uploaded it and also that of 0.7 which has been released a little while ago.
Could you try again?

**Comment by wuxxin** [comment]
thank you very much, pip (on python3) is now finding version 0.7
and https://pypi.org/simple/cgroup-utils/
also lists 0.6 and 0.7 now
